# Generated by Django 5.0.7 on 2024-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrecord',
            name='asset_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assetrecord',
            name='nomenclature',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
