# Generated by Django 5.0.7 on 2024-07-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_assetrecord_asset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrecord',
            name='date_purchase',
            field=models.DateTimeField(),
        ),
    ]
