# Generated by Django 5.0.7 on 2024-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_assetrecord_date_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assetrecord',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
