# Generated by Django 5.0.7 on 2024-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_assetrecord_category_remove_assetrecord_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrecord',
            name='date_purchase',
            field=models.DateField(),
        ),
    ]
